Develop
h2ash/react_phone-catalog pull request #1
Opened 2019-08-12 11:45 UTC by h2ash

Demo:  https://h2ash.github.io/react_phone-catalog/

2019-08-13 11:58 UTC, GitHubForDmitry approved these changes

2019-08-13 12:37 UTC, h2ash commented
Циферка к корзинке - это уже с украшательствами со всеми. 
Крестик пока заумал справа от назавания, но будут дизайн менять, так может и кнопку перенесу)

2019-08-13 14:02 UTC, vpolets commented on src/index.js
> +  <BrowserRouter basename='/react_phone-catalog'>
пулл реквест оновити не хочеш?

2019-08-14 14:24 UTC, vkryvytskyi requested changes

2019-08-14 14:24 UTC, vkryvytskyi commented on src/App.js
> +      delete requiredItem.carrier;
Зачем вручную удалять свойства объекта?

2019-08-14 14:24 UTC, vkryvytskyi commented on src/App.js
> +    const responsePhones = await
Это бы вынести в отдельный файл

2019-08-14 14:24 UTC, volodymyrkryvytskyy commented on src/App.js
> +    }, 1000)
Искусственную задержку можешь убрать

2019-08-14 14:24 UTC, volodymyrkryvytskyy commented on src/components/PhoneDetails.jsx
> +    const currentImage = `${BASE_IMAGE_URL}/${this.props.phone.imageUrl}`;
Делай деструктуризацию props

2019-08-14 14:24 UTC, volodymyrkryvytskyy commented on src/components/PhoneDetails.jsx
> +    const BASE_IMAGE_URL =
У тебя ж уже есть такая переменная. Сделай файл с константами `constants.js`, импортируй сюда нужную - и она будет доступна во всем документе и не надо будет объявлять ее каждый раз заново

2019-08-14 14:24 UTC, volodymyrkryvytskyy commented on src/components/PhoneDetailsPage.jsx
> +    const responseDetails = await
В отдельный файл

2019-08-14 14:24 UTC, volodymyrkryvytskyy commented on src/components/PhoneDetailsPage.jsx
> +    this.props.loadDataPhones()
Зачем когда переходишь на страницу отдельного телефона - загружать информацию обо всех телефонах?

2019-08-14 14:24 UTC, volodymyrkryvytskyy commented on src/components/PhoneDetailsPage.jsx
> +    details: '',
Почему details изначально строка, если потом ты туда записываешь объект?

2019-08-14 14:24 UTC, volodymyrkryvytskyy commented on src/components/PhoneDetailsPage.jsx
> +                        .map(phone =>
Мне кажется что в файле details есть вся нужная информация, тебе не надо передавать туда еще и phone
<img width="1440" alt="Screen Shot 2019-08-14 at 5 13 23 PM" src="https://user-images.githubusercontent.com/38065883/63028234-1ad57480-beb7-11e9-8eb5-f71d60bbe266.png">

2019-08-18 14:31 UTC, h2ash commented on src/App.js
> +      delete requiredItem.carrier;
Хотел, чтоб меньше св-в было в объектах, ну ладно)

2019-08-18 14:32 UTC, h2ash commented on src/App.js
> +      delete requiredItem.carrier;
Удалил эти строки.

2019-08-18 14:33 UTC, h2ash commented on src/App.js
> +    const responsePhones = await
Какой файл? Например?

2019-08-18 14:35 UTC, h2ash commented on src/App.js
> +    }, 1000)
Убрал

2019-08-18 14:43 UTC, h2ash commented on src/components/PhoneDetails.jsx
> +    const currentImage = `${BASE_IMAGE_URL}/${this.props.phone.imageUrl}`;
Готово

2019-08-18 14:49 UTC, h2ash commented on src/components/PhoneDetails.jsx
> +    const BASE_IMAGE_URL =
Спасибо, сделал

2019-08-18 14:52 UTC, h2ash commented on src/components/PhoneDetailsPage.jsx
> +    this.props.loadDataPhones()
Чтобы можно было переходить по прямой ссылке сразу на телефон, иначе phones не будут загружаться и будет ошибка.

2019-08-18 14:54 UTC, h2ash commented on src/components/PhoneDetailsPage.jsx
> +    details: '',
Исправил, спасибо

2019-08-19 14:43 UTC, h2ash commented on src/components/PhoneDetailsPage.jsx
> +                        .map(phone =>
Да, в самом начале чуток ошибся с условием про детали(оказалось, что они есть для всех телефонов) и понеслась. Спасибо, исправил. :)

2019-08-20 09:24 UTC, vkryvytskyi approved these changes

2019-08-20 09:24 UTC, vkryvytskyy commented on src/components/PhoneDetails.jsx
> +    console.log(details);
Консоль логи удаляем

2019-08-20 09:25 UTC, vkryvytskyy commented on src/App.js
> +    const responsePhones = await
Например helper.js где у тебя будут все функции для работы с API

2020-01-05 05:49 UTC, merged

2020-01-05 05:58 UTC, h2ash commented
...